export default [
	'Academic History',
	'Adventure',
	'Alien Invasion',
	'Alternate History',
	'Alternate Universe',
	'Anti-nicene',
	'Antinovel',
	'Apocalyptic',
	'Apocrypha',
	'Apologetics',
	'Aporetic',
	'Atompunk',
	'Autobiographical Novel',
	'Autobiography',
	'Biblical Theology',
	'Bildungsroman',
	'Biography',
	'Biopunk',
	'Bizarro Fiction',
	'Blessing',
	'Body Horror',
	'British Literature',
	'Buddhist Texts',
	'Campus Murder Mystery',
	'Campus Novel',
	'Canonical Criticism',
	'Ceremonial',
	'Chant',
	'Children Literature',
	'Christian Fiction',
	'Christian Literature',
	'Christian Science Fiction',
	'Christology',
	'Class S',
	'Classic',
	'Climate Fiction',
	'Clockpunk',
	'Comic Fantasy',
	'Comics',
	'Commentary',
	'Confession',
	'Contemporary',
	'Contemporary Christian Fiction',
	'Contemporary Fantasy',
	'Contemporary Slave Narrative',
	'Contradiction',
	'Convenant',
	'Cosmic',
	'Cosmology',
	'Creative Nonfiction',
	'Creed',
	'Crime',
	'Critique',
	'Cult Literature',
	'Curse',
	'Cyberpunk',
];
